name: Simple Windows Pod Deployment

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy-pod:
    runs-on: self-hosted

    env:
      NAMESPACE: default

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate pod.yaml with random name (Windows)
        shell: powershell
        run: |
          $ID = -join ((48..57) + (97..102) | Get-Random -Count 6 | ForEach-Object {[char]$_})
          $POD_NAME = "mypod-$ID"
          @"
apiVersion: v1
kind: Pod
metadata:
  name: $POD_NAME
  namespace: ${env:NAMESPACE}
  labels:
    name: mypod
spec:
  containers:
  - name: mypod
    image: rancher/hello-world
"@ | Out-File -FilePath pod.yaml -Encoding utf8

      - name: Apply to cluster
        run: kubectl apply -f pod.yaml

      - name: List Pods
        run: kubectl get pods -n ${NAMESPACE}
