name: Kubectl Pod Deployment

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy-pod:
    runs-on: self-hosted

    env:
      NAMESPACE: default  # replace with your namespace if needed

    steps:
      # Step 1: Checkout repo (good practice even if no code is used)
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Generate a random pod ID
      - name: Generate random pod ID
        id: vars
        run: |
         ID=$(openssl rand -hex 4)
         echo "ID=$ID" >> $GITHUB_ENV
         echo "::set-output name=podname::mypod-$ID"

      # Step 3: Create a pod.yaml file with random pod name
      - name: Create pod YAML
        run: |
          cat <<EOF > pod.yaml
          apiVersion: v1
          kind: Pod
          metadata:
            name: mypod-${ID}
            namespace: ${NAMESPACE}
            labels:
              name: mypod
          spec:
            containers:
            - name: mypod
              image: rancher/hello-world
          EOF

      # Step 4: Apply the pod to your Kubernetes cluster
      - name: Apply to cluster
        run: kubectl apply -f pod.yaml

      # Step 5: Get list of pods in the namespace
      - name: List Pods
        run: kubectl get pods -n ${NAMESPACE}
