apiVersion: v1
kind: Pod
metadata:
  name: mypod-xgtrpl # Random name generated in GitHub Actions
  namespace: default # Set via script or hardcoded
  labels:
    name: mypod
spec:
  containers:
  - name: mypod
    image: rancher/hello-world
