name: Test Kubernetes Access

on:
  workflow_dispatch: # Manual trigger
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Hello Pod
    runs-on: self-hosted

    env:
      NAMESPACE: my-namespace

    steps:
      # Checkout your code (if needed)
      - name: Checkout Repo
        uses: actions/checkout@v4

      # Generate a random ID
      - name: Generate Random ID
        id: random
        run: echo "id=$(openssl rand -hex 4)" >> $GITHUB_OUTPUT

      # Create a Pod YAML file with random name
      - name: Create Pod YAML
        run: |
          cat <<EOF > pod.yaml
          apiVersion: v1
          kind: Pod
          metadata:
            name: mypod-${{ steps.random.outputs.id }}
            namespace: $NAMESPACE
            labels:
              name: mypod
          spec:
            containers:
            - name: mypod
              image: rancher/hello-world
          EOF

      # Apply the YAML using kubectl
      - name: Apply Pod YAML
        run: kubectl apply -f pod.yaml

      # Get the list of pods in the namespace
      - name: Get Pods
        run: kubectl get pods -n $NAMESPACE
