apiVersion: v1
kind: Pod
metadata:
  generateName: mypod- # Try to make this dynamically generated (random)
  namespace: test-generator # Enter your namespace here
  labels:
    name: mypod
spec:
  containers:
  - name: mypod
    image: rancher/hello-world
